server:
  port: 8080

spring:
  application:
    name: hraccoon

# DB 설정(local)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{url}/{databaseName}?characterEncoding=UTF-8&serverTimezone=UTC
    username: { userName }
    password: { userPassword }
    hikari:
      connection-test-query: SELECT NOW() FROM DUAL

# JPA 설정
  jpa:
    hibernate:
# 배포 시 변경 (create -> none)
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
# SQL 로깅 설정(더미 데이터)
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: utf-8
      platform: mariadb
      data-locations: classpath:database/data.sql

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace
