server:
  port: 8080

spring:
  application:
    name: hraccoon

# DB 설정(local)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hraccoon?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ulsansaram17!           
    hikari:
      connection-test-query: SELECT NOW() FROM DUAL

# JPA 설정
  jpa:
    hibernate:
# 배포 시 변경 (create -> none)
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
# SQL 로깅 설정(더미 데이터)
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: utf-8
      platform: mariadb
      data-locations: classpath:database/data.sql

# Redis 설정
  data:
    redis:
      host: redis
      port: 6379

# jwt 설정
  jwt:
    secret-key: IenVnrcQA4lnxVEyzyGFSPbq8YexqhaEPVn3IgBBpJ3wY1ODOKmS1j0nLIqLKEkfvNjYvdnT7QfXSltrcT5r03B5jqFe40PGvSXLGpJkMRsFTyUgPb01oqG1NbFyeOiN
    life:
      accessToken: 300000
      refreshToken: 3000000
    issuer: OrangeVinyl


# 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace
