server:
  port: 8080

spring:
  application:
    name: hraccoon

  # DB 설정(local)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:///hraccoon?characterEncoding=UTF-8&serverTimezone=UTC
    username: 
    password: 
    hikari:
      connection-test-query: SELECT NOW() FROM DUAL

  # JPA 설정
  jpa:
    hibernate:
      # 배포 시 변경 (create -> none)
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
    # SQL 로깅 설정(더미 데이터)
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: utf-8
      platform: mariadb
      data-locations: classpath:database/init-data.sql

  # Redis 설정
  data:
    redis:
      host: redis
      port: 6379

  # jwt 설정
  jwt:
    secret-key: 
    life:
      accessToken: 3600000 # 1시간
      refreshToken: 10800000 # 3시간
    issuer: OrangeVinyl

  # Batch
  batch:
    job:
      enabled: false
      name: checkInJob, checkOutJob, clearAttendanceTableJob
  main:
    allow-circular-references: true

  # 이메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: hraccoon8@gmail.com
    password: { key }
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true2
    templates:
      path: classpath:/templates/email
      logo-path: classpath:/static/images/logo.png
# 로깅 설정
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace

